#!/usr/bin/env bash
# Regenerate the dashboard data from the pipeline output and commit it.
# The bundle is NOT built here anymore: pushing the refreshed data triggers
# .github/workflows/deploy-dashboard.yml, which builds the single-file artifact
# (vite-plugin-singlefile) and publishes it to Pages. This keeps the local run
# fast and removes the dependency on the local artifacts-builder skill.
# Safe to call from deploy/run.sh after the pipeline stage; designed to be
# non-fatal (callers should invoke with `|| true`) and launchd-friendly
# (resolves node without relying on an interactive shell PATH).
set -uo pipefail

DASHBOARD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DASHBOARD_DIR"

# Public npm registry — the machine's ~/.npmrc points pnpm at a corporate
# registry that lacks create-vite/parcel.
export npm_config_registry="https://registry.npmjs.org/"

# Make nvm-installed node/pnpm reachable under launchd's restricted PATH.
NVM_BIN_DIR="$(dirname "$(ls -t "$HOME"/.nvm/versions/node/*/bin/node 2>/dev/null | head -1)" 2>/dev/null)"
[ -n "${NVM_BIN_DIR:-}" ] && export PATH="$NVM_BIN_DIR:$PATH"

NODE_BIN="$(command -v node || true)"
if [ -z "$NODE_BIN" ]; then
  echo "[dashboard] node not found; skipping refresh" >&2
  exit 0
fi

echo "[dashboard] regenerating data…"
"$NODE_BIN" scripts/gen-data.mjs || { echo "[dashboard] gen failed" >&2; exit 0; }
echo "[dashboard] data refreshed → dashboard/src/daily.json (CI will build & deploy the bundle)"

# ── Auto-commit & push the refreshed data (default ON) ──────────────────────
# Disable with: DASHBOARD_AUTOCOMMIT=0  (also accepts false/no/off)
case "${DASHBOARD_AUTOCOMMIT:-1}" in
  0 | false | no | off) echo "[dashboard] autocommit disabled; skipping git"; exit 0 ;;
esac

REPO_ROOT="$(cd "$DASHBOARD_DIR/.." && pwd)"
cd "$REPO_ROOT"

GIT="$(command -v git || true)"
if [ -z "$GIT" ] || ! "$GIT" rev-parse --git-dir >/dev/null 2>&1; then
  echo "[dashboard] git unavailable / not a repo; skipping commit" >&2
  exit 0
fi

# Stage the generated dashboard data together with the pipeline's source outputs
# so the repo stays self-consistent after an unattended run. Pushing any of
# these triggers the Pages build+deploy workflow. Pipeline outputs are generated
# from public GitHub data; secret files stay blocked by .gitignore + the
# pre-commit hook. Set DASHBOARD_COMMIT_DATA=0 to commit only the generated
# dashboard data.
TARGETS="dashboard/src/daily.json"
case "${DASHBOARD_COMMIT_DATA:-1}" in
  0 | false | no | off) : ;;
  *) TARGETS="$TARGETS daily projects data" ;;
esac
# shellcheck disable=SC2086
"$GIT" add $TARGETS 2>/dev/null || true
if "$GIT" diff --cached --quiet; then
  echo "[dashboard] no changes to commit"
  exit 0
fi

DATE="$("$NODE_BIN" -e 'try{const e=require("./dashboard/src/daily.json").editions;process.stdout.write(e&&e[0]?e[0].date:"")}catch(_){process.stdout.write("")}' 2>/dev/null)"
"$GIT" commit -q \
  -m "chore(dashboard): refresh data${DATE:+ ($DATE)}" \
  -m "Auto-generated by dashboard/refresh.sh; CI builds & deploys the bundle." \
  || { echo "[dashboard] commit failed" >&2; exit 0; }
echo "[dashboard] committed data update${DATE:+ ($DATE)}"

# Push (non-fatal); single rebase-retry if the remote moved meanwhile.
if "$GIT" push >/dev/null 2>&1; then
  echo "[dashboard] pushed → origin (CI will build & deploy)"
elif "$GIT" pull --rebase --autostash >/dev/null 2>&1 && "$GIT" push >/dev/null 2>&1; then
  echo "[dashboard] pushed after rebase → origin"
else
  echo "[dashboard] push failed; commit kept locally — push manually later" >&2
fi
