#!/usr/bin/env bash
# Regenerate the dashboard data from the pipeline output and rebuild bundle.html.
# Safe to call from deploy/run.sh after the pipeline stage; designed to be
# non-fatal (callers should invoke with `|| true`) and launchd-friendly
# (resolves node/pnpm without relying on an interactive shell PATH).
set -uo pipefail

DASHBOARD_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DASHBOARD_DIR"

# Public npm registry — the machine's ~/.npmrc points pnpm at a corporate
# registry that lacks create-vite/parcel.
export npm_config_registry="https://registry.npmjs.org/"

# Make nvm-installed node/pnpm reachable under launchd's restricted PATH.
NVM_BIN_DIR="$(dirname "$(ls -t "$HOME"/.nvm/versions/node/*/bin/node 2>/dev/null | head -1)" 2>/dev/null)"
[ -n "${NVM_BIN_DIR:-}" ] && export PATH="$NVM_BIN_DIR:$PATH"

NODE_BIN="$(command -v node || true)"
if [ -z "$NODE_BIN" ]; then
  echo "[dashboard] node not found; skipping refresh" >&2
  exit 0
fi

echo "[dashboard] regenerating data…"
"$NODE_BIN" scripts/gen-data.mjs || { echo "[dashboard] gen failed" >&2; exit 0; }

BUNDLE_SCRIPT="$HOME/.claude/skills/artifacts-builder/scripts/bundle-artifact.sh"
if [ ! -f "$BUNDLE_SCRIPT" ]; then
  echo "[dashboard] bundle script not found; data refreshed, skipping bundle" >&2
  exit 0
fi

[ -d node_modules ] || pnpm install >/dev/null 2>&1 || true

echo "[dashboard] rebuilding bundle.html…"
bash "$BUNDLE_SCRIPT" >/dev/null 2>&1 || { echo "[dashboard] bundle failed" >&2; exit 0; }
echo "[dashboard] refresh complete → dashboard/bundle.html"

# ── Auto-commit & push the refreshed artifact (default ON) ──────────────────
# Disable with: DASHBOARD_AUTOCOMMIT=0  (also accepts false/no/off)
case "${DASHBOARD_AUTOCOMMIT:-1}" in
  0 | false | no | off) echo "[dashboard] autocommit disabled; skipping git"; exit 0 ;;
esac

REPO_ROOT="$(cd "$DASHBOARD_DIR/.." && pwd)"
cd "$REPO_ROOT"

GIT="$(command -v git || true)"
if [ -z "$GIT" ] || ! "$GIT" rev-parse --git-dir >/dev/null 2>&1; then
  echo "[dashboard] git unavailable / not a repo; skipping commit" >&2
  exit 0
fi

# Stage only the generated artifacts (data snapshot + self-contained bundle).
"$GIT" add dashboard/src/daily.json dashboard/bundle.html 2>/dev/null || true
if "$GIT" diff --cached --quiet; then
  echo "[dashboard] no artifact changes to commit"
  exit 0
fi

DATE="$("$NODE_BIN" -e 'try{const e=require("./dashboard/src/daily.json").editions;process.stdout.write(e&&e[0]?e[0].date:"")}catch(_){process.stdout.write("")}' 2>/dev/null)"
"$GIT" commit -q \
  -m "chore(dashboard): refresh data + bundle${DATE:+ ($DATE)}" \
  -m "Auto-generated by dashboard/refresh.sh after the pipeline run." \
  || { echo "[dashboard] commit failed" >&2; exit 0; }
echo "[dashboard] committed artifact update${DATE:+ ($DATE)}"

# Push (non-fatal); single rebase-retry if the remote moved meanwhile.
if "$GIT" push >/dev/null 2>&1; then
  echo "[dashboard] pushed → origin (Pages will redeploy)"
elif "$GIT" pull --rebase --autostash >/dev/null 2>&1 && "$GIT" push >/dev/null 2>&1; then
  echo "[dashboard] pushed after rebase → origin"
else
  echo "[dashboard] push failed; commit kept locally — push manually later" >&2
fi
